name: 'Linux, macOS and Windows'
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: '1.12'
      - name: Lint source code
        env:
          MAGEFILE_VERBOSE: true
        run: |
          GOBIN="$(pwd)/bin" go install github.com/magefile/mage
          ./bin/mage -d tools install
          ./bin/mage -d tools lint

  test:
    needs: lint
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        go: ['1.12'] # add more versions if desired
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Go version ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Run test
        env:
          GO111MODULE: on
          MAGEFILE_VERBOSE: true
        shell: bash
        run: |
          GOBIN="$(pwd)/bin" go install github.com/magefile/mage
          ./bin/mage -d tools test
